"""empty message

Revision ID: 9e7700f196c2
Revises: 
Create Date: 2020-01-29 08:27:20.622520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7700f196c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('user',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('checkedin_user_attendance',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('attendance_id', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.timestamp'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'attendance_id')
    )
    op.create_table('checkedout_user_attendance',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('attendance_id', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.timestamp'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'attendance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkedout_user_attendance')
    op.drop_table('checkedin_user_attendance')
    op.drop_table('user')
    op.drop_table('attendance')
    # ### end Alembic commands ###
